// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.InteropServices

[<assembly: AssemblyTitleAttribute("Program Updater Framework")>]
[<assembly: AssemblyProductAttribute("Program Updater Framework")>]
[<assembly: GuidAttribute("0F026EA5-501A-4947-B8E2-5860D3520E99")>]
[<assembly: AssemblyCompanyAttribute("Enkomio")>]
[<assembly: AssemblyDescriptionAttribute("A framework to automatize the process of updating a program in an efficent and secure way.")>]
[<assembly: AssemblyVersionAttribute("1.3.483.16")>]
[<assembly: AssemblyFileVersionAttribute("1.3.483.16")>]
[<assembly: AssemblyInformationalVersionAttribute("1.3.483.16")>]
[<assembly: AssemblyMetadataAttribute("BuildDate","2019-10-20")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Program Updater Framework"
    let [<Literal>] AssemblyProduct = "Program Updater Framework"
    let [<Literal>] Guid = "0F026EA5-501A-4947-B8E2-5860D3520E99"
    let [<Literal>] AssemblyCompany = "Enkomio"
    let [<Literal>] AssemblyDescription = "A framework to automatize the process of updating a program in an efficent and secure way."
    let [<Literal>] AssemblyVersion = "1.3.483.16"
    let [<Literal>] AssemblyFileVersion = "1.3.483.16"
    let [<Literal>] AssemblyInformationalVersion = "1.3.483.16"
    let [<Literal>] AssemblyMetadata_BuildDate = "2019-10-20"
